# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      # ruamel.yaml.clib appears to cause the build to fail when
      # using new API in ruamel.yaml
      # refs:
      # - https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/340/
      # - https://yaml.readthedocs.io/en/latest/api.html
      - pip uninstall ruamel.yaml.clib -y

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - method: pip
     path: .
   - requirements: docs/requirements.txt
